---
# Download and install Docker
- name: "Get GPG key for Docker"
# Example action to import a key from a url
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == 'Debian'

#Add Docker repo to apt sources
- name: "Add Docker Repo."
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when: ansible_os_family == 'Debian'
