# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: false 
  config.ssh.password = "vagrant"

  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.box_version = "1602185544"
    virtualbox.vm.hostname = "virtualbox-ubuntu1804"
    virtualbox.vm.box = "nedster1980/ubuntu1804"
    virtualbox.vm.network :private_network, ip: "172.16.3.2"

    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 8096
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--vram", "100"]
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    end

    config.vm.provision "shell", inline: "echo Hello, World"
  end

end
