---
- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: "Install some helpful utilities."
      apt:
        name:
              - git
              - wget
              - curl
              - vim
        state: present
      when: ansible_os_family == 'Debian'

    - name: "Install XFCE interface."
      apt:
        name:
              - xfce4
              - xfce4-goodies
              - xorg
              - dbus-x11
              - x11-xserver-utils
        state: present
      when: ansible_os_family == 'Debian'

    - import_tasks: package_node_12.yml
    - import_tasks: package_gradle.yml
    - import_tasks: package_xrdp.yml
    - import_tasks: package_vscode.yml
    - import_tasks: package_eclipse_snap.yml
