---
- hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: "Install some helpful utilities."
      apt:
        name:
          - cifs-utils
          - libssl-dev
          - libreadline-dev
          - zlib1g-dev
          - vim
          - linux-source
          - cryptsetup
          - snapd
          - network-manager
          - nfs-common
          - lsof
          - nmap
          - sysstat
          - mlocate
          - net-tools
          - tree
          - apt-utils
          - dnsutils
          - open-vm-tools-desktop
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: "Install snap-store via snap"
      command: snap install snap-store

    - import_tasks: package_node_12.yml
    - import_tasks: package_chrome.yml
    - import_tasks: package_docker.yml
    - import_tasks: package_microsoft.yml
    - import_tasks: package_k8s.yml
    - import_tasks: package_xrdp.yml
    - import_tasks: package_mate.yml

    - name: "Install all packages, docker, docker-compose, k8s, dotnet-sdk-3.1, openjdk 11"
      apt:
        name:
              - docker-ce=18.06.3~ce~3-0~ubuntu
              - kubelet=1.16.13-00
              - kubeadm=1.16.13-00
              - kubectl=1.16.13-00
              - google-chrome-stable
              - dotnet-sdk-3.1
              - openjdk-11-jre-headless
              - code
        state: present
      when: ansible_os_family == 'Debian'

    - name: "Install docker-compose"
      command: sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      
    - name: "Make docker-compose in /usr/local/bin executable."
      file:
        path: /usr/local/bin/docker-compose
        mode: '0755'

    - name: "Add the vagrant user to the docker group."
      user:
          name: vagrant
          groups: docker
          append: yes

    - name: "Install eclipse IDE with option classic via snap"
      command: snap install --classic eclipse

    - name: Change the working directory to somedir/ and run the command as db_owner if /path/to/database does not exist.
      command: apt-mark hold kubelet kubeadm kubectl docker-ce docker-ce-cli

    - name: "Create file .xsession and insert mate-session."
      lineinfile:
          path: /home/vagrant/.xsession
          line: mate-session
          create: yes
          mode: '0755'
    
    - name: "Restart service xrdp."
      service:
          name: xrdp
          state: restarted
          enabled: yes
    
