---
# Download and install mate
- name: "Install Mate GUI."
  apt:
    name:
          - mate-core
          - mate-desktop-environment 
          - mate-notification-daemon
    state: present
  when: ansible_os_family == 'Debian'